language: php

php:
  - 7.3
  - 7.4

before_install:
  # Disable XDebug speed up test execution.
  - phpenv config-rm xdebug.ini || return 0
  # Enable MongoDB extension
  - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini || return 0

install:
  - make dependencies

script:
  - make test
  - make qa
  - make license
  - make changelog

services:
  - mongodb
