language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
  fast_finish: true

before_install:
  # Disable XDebug speed up test execution.
  - phpenv config-rm xdebug.ini || return 0
  # Enable MongoDB extension
  - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini || return 0

install:
  - travis_retry composer self-update
  - travis_retry composer update
  - composer info -i

script:
  - phpunit --exclude-group=none

branches:
  only:
    - master

services:
  - mongodb
